### PR TITLE
Upgraded pact-js and added a comparable contract based on Spring

### PR DESCRIPTION
**Pull request by kai-moritz**
I found your example very helpful.
Yet, it is outdated (the used versions are not accessible any more) and it lacks an example for the JVM.
This results of some educational experiments may enhance your example help you, to update and enhance your (officially linked!) example   ...

### CODE REVIEW

**Comment by YOU54F** [comment]
Oh thank you very much for this @kai-moritz 

I wonder if it might be worth making an example-siren-js and example-siren-java repo, and we can extend to other languages if its useful for people.

or we could split out and have an example-consumer-js-siren / example-consumer-java-siren / example-provider-js-siren

It would fall in line with our other examples, and makes it easy to grok

https://github.com/orgs/pactflow/repositories?q=example&type=all&language=&sort=name
https://docs.pactflow.io/docs/examples/#demos 

Really pleased that the examples have helped and appreciate you updating things.

I'd like to get these examples tested in GitHub Actions e2e too, and regularly so we can keep dependencies up to date so everything works out the box.

I note there are still some juplo refs in the code, that would be worth pulling out

**Comment by kai-moritz** [comment]
Hi Yousaf,

I pulled out the refs to juplo.
I think, your idea to split out the contained sub-project as standalone-examples is worth a try.
Maybe, I will send you some follow-up PRs later this day...


Best regards

kai

**Comment by kai-moritz** [comment]
Hi Yousaf,

the last a addition is work-in-progress at the moment.
You will have to fork the following standalone-versions of the given example into your github-Namespace, and execute `git submodule update --init` afterwards, to get it running...

https://github.com/juplo/example-provider-java-siren
https://github.com/juplo/example-consumer-js-siren
https://github.com/juplo/example-consumer-java-siren

Thes standalone-projects contain the splitted standalone versions of the sub-project of the example, that you sugested.

**Comment by YOU54F** [comment]
Thanks @kai-moritz 

I've ended up just using the examples in the repo, without the submodules.

Sorry it took so long to get these in.

**Pull request merged**
